const assert = require('assert');
const { THEMES, readyThemes } = require('../companion-theme-catalog');
const { createThemeState } = require('../companion-theme-state');
const rabbit = { prototype: '玉兔' };
const koi = { prototype: '锦鲤' };
const ready = (id, pet) => ({ id, name: id === 'duck' ? '小黄鸭' : id, pet, approved: true,
  artwork: `/assets/themes/${id}.png`, steps: [1,2,3].map(n => ({image: `/assets/themes/${id}-${n}.png`})) });
const catalog = [ready('duck', 'jade-rabbit'), ready('bell', 'shared'), ready('pinwheel', 'boon-koi')];
const art = { operations: [{ type: 'stroke', tool: 'brush', points: [{ x: 1, y: 1 }] }] };
const memory = { image: '/tmp/user-original.png', title: '一起画的画' };
const mustNotRoll = () => { throw Error('must not reroll'); };
assert.equal(THEMES.length, 31);
assert.equal(new Set(THEMES.map(t => t.id)).size, 31);
assert.deepEqual(readyThemes(rabbit).map(t=>t.id), ['K-A06','K-R01']);
assert.deepEqual(readyThemes(koi).map(t=>t.id), ['K-A06','K-K03']);
assert.equal(THEMES.filter(t=>t.approved).length,3,'只开放已核对的首批三主题');
assert.equal(readyThemes(rabbit,THEMES.filter(t=>!t.approved)).length,0,'其余未准备主题保持关闭');
assert.deepEqual(readyThemes(rabbit, catalog).map(t => t.id), ['duck', 'bell']);
assert.deepEqual(readyThemes(koi, catalog).map(t => t.id), ['bell', 'pinwheel']);
assert.equal(readyThemes(rabbit, [{...catalog[0], approved: false}]).length, 0);
assert.equal(readyThemes(rabbit, [{...catalog[0], steps: []}]).length, 1);
assert.equal(readyThemes(rabbit, [{...catalog[0], artwork: '/assets/four-view.webp'}]).length, 0);
let state = createThemeState({catalog});
const today = state.invitation(rabbit, '2026-10-04');
assert.deepEqual(state.invitation(rabbit, '2026-10-04'), today, '跳过、再次读信仍是当天同一主题');
assert.equal(state.invitation(rabbit, '2026-10-05').theme.id, 'bell');
assert.equal(state.invitation(rabbit, '2026-10-06').theme.id, 'duck', '全部准备主题轮过后才重复');
assert.equal(state.begin(rabbit, 'forged', '2026-10-04').ok, false, '不能手选或伪造另一个主题');
assert.equal(state.begin(rabbit, today.id, '2026-10-04').ok, true);
state.setStep(today.id, 2);
assert.equal(state.invitation(koi, '2026-10-04'), null, '另一宠物不能恢复玉兔房间主题');
assert.equal(state.begin(koi, today.id, '2026-10-04').ok, false);
assert.equal(state.invitation(rabbit, '2026-10-07').id, today.id, '跨日仍能继续同一次未完成主题');
assert.equal(state.getActive().step, 2);
assert.equal(state.complete(today.id, memory, {operations: []}, {random: mustNotRoll}).ok, false);
assert.equal(state.complete(today.id, memory, {operations: [{type:'sticker'}]}, {random: mustNotRoll}).ok, false);
assert.equal(state.complete(today.id, memory, {operations: [{type:'stroke',tool:'eraser',points:[{}]}]}, {random: mustNotRoll}).ok, false);
assert.equal(state.complete(today.id, {}, art, {random: mustNotRoll}).ok, false, '导出失败保留同一次主题，不消耗奖励');
assert.equal(state.getActive().id, today.id);
let done = state.complete(today.id, memory, art, {date: '2026-10-07', random: () => 0.6});
assert.equal(done.data.tier, 1);
assert.equal(done.data.stars, 1);
assert.equal(done.data.prop.name, '小黄鸭');
assert.equal(done.data.line, '小黄鸭送给你。');
assert.equal(done.data.memory.image, memory.image, '结果保留用户原图，不替换为主题完整图');
assert.equal(state.invitation(rabbit, '2026-10-07'), null, '成功完成日最多一次有奖励的主题');
assert.equal(state.complete(today.id, memory, art, {date: '2026-10-08', random: mustNotRoll}).duplicate, true, '跨日迟到回调不重抽或占新额度');
let next = state.invitation(rabbit, '2026-10-08');
state.begin(rabbit, next.id, '2026-10-08');
state.complete(next.id, memory, art, {date: '2026-10-08', random: () => 0});
next = state.invitation(rabbit, '2026-10-09');
state.begin(rabbit, next.id, '2026-10-09');
done = state.complete(next.id, memory, art, {date: '2026-10-09', random: () => 0.9});
assert.equal(done.data.tier, 2);
assert.equal(done.data.duplicateProp, true);
assert.equal(done.data.prop, null);
assert.equal(done.data.stars, 6, '惊喜档1+3星，重复道具再替换为2星');
assert.equal(done.data.line, '星星送给你。', '重复道具改星后文案表达实际所得');
for (const [roll, tier, stars] of [[0,0,1],[0.599999,0,1],[0.6,1,1],[0.899999,1,1],[0.9,2,4],[0.999999,2,4]]) {
  const single = createThemeState({catalog: [catalog[0]]});
  const offer = single.invitation(rabbit, '2026-10-04');
  single.begin(rabbit, offer.id, '2026-10-04');
  const result = single.complete(offer.id, memory, art, {date: '2026-10-04', random: () => roll});
  assert.equal(result.data.tier, tier);
  assert.equal(result.data.stars, stars);
}
const alreadyOwned = createThemeState({catalog: [catalog[0]], ownedPropIds: ['duck']});
const existingOffer = alreadyOwned.invitation(rabbit, '2026-10-04');
alreadyOwned.begin(rabbit, existingOffer.id, '2026-10-04');
const replacement = alreadyOwned.complete(existingOffer.id, memory, art, {date: '2026-10-04', random: () => 0.6});
assert.equal(replacement.data.prop, null);
assert.equal(replacement.data.stars, 3, '既有道具也替换为2星，不只识别本玩法送过的道具');
console.log('主题库素材门禁、宠物范围、每日轮换、跳过保留、跨日继续、真实笔迹、原画保存及随机奖励边界通过。');
