const assert = require('assert');
const stars = require('../iaa-star-unlock-adapter');
const originalNow = Date.now;
let now = Date.parse('2026-10-04T23:59:59.999+08:00');
Date.now = () => now;
const day = () => stars.getRoomStarView().then(result => result.data);
const photo = { image: 'fixture-photo.webp', title: '窗边茶会', line: '一起在窗边喝了一杯茶。' };
(async () => {
  stars.configureRoom('gift-settlement');
  let calls = 0;
  const start = await stars.recordDrawingStart(await day());
  const first = await stars.recordDrawingComplete(start.data, 'first-work', { random: () => { calls++; return 1; } });
  assert.equal(first.giftStars, 3, '首次必得，不读取随机数');
  assert.equal(calls, 0);
  assert.equal(first.awardedStars, 13);
  assert.equal(first.data.star.balance, 25, '初始2星，加开始10、完成10、回礼3');
  assert.equal(first.data.star.companionDays, 1);
  const repeated = await stars.recordDrawingComplete(start.data, 'first-work', { random: () => { throw Error('重复不应重抽'); } });
  assert.equal(repeated.awardedStars, 0);
  assert.deepEqual(repeated.drawingGift, first.drawingGift, '后台恢复同一作品保留回礼结果');
  assert.equal((await stars.recordDrawingComplete(first.data, 'second-work')).awardedStars, 0);
  now += 1;
  assert.equal((await stars.recordDrawingComplete(await day(), 'first-work')).awardedStars, 0, '跨午夜旧回调不占用新日');
  const miss = await stars.recordDrawingComplete(await day(), 'next-day-work', { random: () => 0.33 });
  assert.equal(miss.giftStars, 0, '33%的上边界不命中');
  assert.equal(miss.baseAwardedStars, 10);
  assert.equal(miss.drawingGift.kind, 'ordinary');
  const secondToday = await stars.recordDrawingComplete(miss.data, 'next-day-second', { random: () => { throw Error('同日第二幅不能重抽'); } });
  assert.equal(secondToday.awardedStars, 0);
  now += 86400000;
  const hit = await stars.recordDrawingComplete(await day(), 'later-hit', { random: () => 0.329999 });
  assert.equal(hit.giftStars, 3);
  assert.equal(hit.baseAwardedStars, 11, '第三个有效日升档，回礼仍固定3');
  assert.equal(hit.drawingGift.kind, 'gift');
  for (let index = 0; index < 4; index++) {
    now += 86400000;
    const result = await stars.recordDrawingComplete(await day(), `miss-${index}`, { random: () => 0.99 });
    assert.equal(result.giftStars, 0, '连续未命中不提高概率、不增加保底');
  }
  stars.configureRoom('invalid-work');
  assert.equal((await stars.recordDrawingComplete(await day(), '')).ok, false);
  assert.equal((await day()).star.balance, 2);
  assert.equal((await stars.recordDrawingComplete(await day(), 'valid-after-error')).giftStars, 3, '失败不消耗首次机会');

  stars.configureRoom('tea-effective');
  stars.beginTeaActivity({ id: 'free-tea', photo });
  assert.equal((await day()).star.companionDays, 0, '进入不计日');
  stars.chooseTea('plain');
  assert.equal((await day()).star.companionDays, 0, '选茶不计日');
  const completed = stars.confirmTeaActivity();
  assert.equal(completed.effectiveAdded, true);
  let view = await day();
  assert.equal(view.star.balance, 2, '免费茶会不发星');
  assert.equal(view.star.baseClaimed, false, '不领取基础奖励');
  assert.equal(view.star.companionDays, 1);
  assert.equal(stars.confirmTeaActivity().duplicate, true);
  const completionDate = completed.data.current.completedDate;
  now += 86400000;
  stars.confirmTeaActivity();
  assert.equal((await day()).star.companionDays, 1, '次日查看结果不补计一天');
  const collected = stars.collectTeaActivity();
  assert.equal(collected.memory.date, completionDate, '稍后收下保留完成日期');
  assert.equal((await day()).star.companionDays, 1);
  view = (await stars.recordDrawingStart(await day())).data;
  await stars.recordDrawingComplete(view, 'fund-tea');
  const funded = (await day()).star.balance;
  stars.beginTeaActivity({ id: 'paid-tea', photo });
  stars.chooseTea('flower');
  assert.equal(stars.confirmTeaActivity().effectiveAdded, false, '当天画画已计日，茶会不重复计');
  assert.equal((await day()).star.balance, funded - 20);
  stars.collectTeaActivity();
  now += 86400000;
  await stars.recordDrawingStart(await day());
  now += 86400000;
  await stars.recordDrawingStart(await day());
  const beforePaid = await day();
  stars.beginTeaActivity({ id: 'paid-next-day', photo });
  stars.chooseTea('plain');
  assert.equal(stars.confirmTeaActivity().effectiveAdded, true, '付费茶会同样计有效日');
  const afterPaid = await day();
  assert.equal(afterPaid.star.companionDays, beforePaid.star.companionDays + 1);
  assert.equal(afterPaid.star.balance, beforePaid.star.balance - 20);
  console.log('画画首次/33%边界/每日次数/跨日去重/无保底，以及茶会有效日/不发星/恢复通过。');
})().catch(error => { console.error(error); process.exitCode = 1; }).finally(() => { Date.now = originalNow; });
