const assert = require('assert');
const catalog = require('../companion-photo-catalog');
const stars = require('../iaa-star-unlock-adapter');
const savedCatalog = catalog.PHOTOS.splice(0);
let definition;
let loader;
let rawSaved;
global.Page = page => { definition=page; };
global.wx={showToast(){},getImageInfo(options){loader=options;},saveImageToPhotosAlbum(options){rawSaved=options.filePath;}};
require('../../pages/iaa-memory-album-demo/iaa-memory-album-demo');
const page=Object.assign({},definition,{roomEntry:true,data:JSON.parse(JSON.stringify(definition.data)),setData(patch){Object.assign(this.data,patch);}});
(async()=>{
  catalog.PHOTOS.push({id:'page-exchange',kind:'exchange',image:'/page.webp',line:'午后的光刚好，给你留一张我的照片。',approved:true});
  stars.configureRoom('page-exchange-test',{prototype:'玉兔'});
  const view=(await stars.getRoomStarView()).data;
  await stars.recordCompanion(view);
  await page.refreshExchange();
  page.setData({selectedActivity:{key:'exchange'}});
  page.onExchangePhoto();
  const originalBalance=(await stars.getRoomStarView()).data.star.balance;
  assert.equal(page.data.selectedMemory,null,'加载前不揭晓');
  loader.fail();loader.complete();
  assert.equal((await stars.getRoomStarView()).data.star.balance,originalBalance,'失败不扣星');
  page.onExchangePhoto();
  const stale=loader;
  page.onCloseDetail();stale.success();stale.complete();
  assert.equal((await stars.getRoomStarView()).data.star.balance,originalBalance,'关闭未完成准备不扣星');
  assert.equal(page.data.selectedMemory,null,'旧回调不重开详情');
  page.setData({selectedActivity:{key:'exchange'}});page.onExchangePhoto();loader.success();loader.complete();
  assert.equal((await stars.getRoomStarView()).data.star.balance,originalBalance-10);
  assert.equal(page.data.selectedMemory.id,'page-exchange');
  await page.refreshExchange();page.onExchangePhoto();
  assert.equal((await stars.getRoomStarView()).data.star.balance,originalBalance-10,'已拥有查看不扣星');
  page.setData({selectedMemory:{image:'/original-wide-art.png',source:'drawing'}});page.onSaveMemory();
  assert.equal(rawSaved,'/original-wide-art.png','既有画作保持原图保存');
  stars.configureRoom('page-identity-a',{prototype:'玉兔'});
  await stars.recordCompanion((await stars.getRoomStarView()).data);
  await page.refreshExchange();page.onExchangePhoto();const other=loader;
  stars.configureRoom('page-identity-b',{prototype:'锦鲤'});await stars.getRoomStarView();other.success();other.complete();
  assert.equal((await stars.getRoomStarView()).data.star.balance,2,'过期页面不能给新宠物扣星');
  global.Page=p=>{definition=p;};require('../../pages/life-scene/life-scene');
  const room=Object.assign({},definition,{data:{pendingCompanionMemory:{id:'old',source:'paper',date:'2020-01-01'}},setData(patch){Object.assign(this.data,patch);}});
  room.syncPendingPaperPhoto();assert.equal(room.data.pendingCompanionMemory,null,'旧日纸条不阻塞新动作，状态仍由纪念册保留');
  room.data.pendingCompanionMemory={id:'collected',source:'paper',date:require('../companion-star-rules').shanghaiDate()};
  room.syncPendingPaperPhoto();assert.equal(room.data.pendingCompanionMemory,null,'纪念册收下后同步房间');
  catalog.PHOTOS.push({id:'room-paper',kind:'outing',image:'/paper.webp',approved:true});
  stars.configureRoom('room-paper-entry',{prototype:'玉兔'});
  room.data={todayCompanionView:{},todayCompanionStarView:(await stars.getRoomStarView()).data,currentState:{atHome:false}};
  room.pageActive=true;let paperResult;
  room.applyCompanionInteractionResult=result=>{paperResult=result;return result;};
  await room.onTodayCompanionInteract();assert.equal(paperResult.paperPhoto.id,'room-paper','真实外出纸条入口触发照片机制');
  console.log('照片真实页面：失败不扣星/关闭取消准备/成功揭晓/已拥有/房间身份隔离/旧照片不阻断/作品原图保存通过。');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{catalog.PHOTOS.splice(0, catalog.PHOTOS.length, ...savedCatalog);});
