const assert = require('assert');
const { createPhotoState } = require('../companion-photo-state');
const catalog = require('../companion-photo-catalog');
const stars = require('../iaa-star-unlock-adapter');
const savedCatalog = catalog.PHOTOS.splice(0);
const originalNow = Date.now;
let now = Date.parse('2026-10-04T23:59:59.999+08:00');
Date.now = () => now;
const outing = { id: 'outing', kind: 'outing', image: '/outing.webp', approved: true, line: '出门前拍的，给你留一张。' };
const solar = { id: 'qiufen', kind: 'solar', image: '/qiufen.webp', approved: true, windows: [{start:'2026-09-23',end:'2026-10-08'}] };
const exchange = { id: 'exchange', kind: 'exchange', image: '/afternoon.webp', approved: true };
(async () => {
  const state = createPhotoState();
  assert.equal(state.offer([outing,solar], { random: () => { throw Error('节气必得无需随机'); } }).id, 'qiufen');
  assert.equal(state.offer([outing,solar]).id, 'qiufen', '重复回调恢复同张');
  now++;
  assert.equal(state.offer([outing,solar], {random: () => .33}), null, '节气已出现后按33%，首次资格已使用');
  assert.equal(state.offer([outing], {random: () => 0}), null, '当天未命中不能重抽');
  now += 86400000;
  assert.equal(state.offer([outing], {random: () => .3299}).id, 'outing');
  assert.equal(state.getPending().length, 2, '跨日保留两张待收下');
  now += 86400000;
  assert.equal(state.offer([outing,solar], {random: () => 0}), null, '待收下也去重，空池不发补偿');
  const date = state.find('qiufen').date;
  assert.equal(state.receive('qiufen').date, date);
  assert.equal(state.getPending().length, 1);
  const fresh = createPhotoState();
  assert.equal(fresh.offer([], {random: () => 0}), null);
  now += 86400000;
  assert.equal(fresh.offer([outing], {random: () => { throw Error('首张单候选无需随机'); }}).id, 'outing', '素材空池不消耗首次资格');
  catalog.PHOTOS.push(outing,solar,exchange, {...outing,id:'not-approved',approved:false});
  assert.equal(catalog.eligiblePhotos({},'2026-10-08').some(item=>item.kind==='solar'), false, '下一节气00:00关闭');
  assert.equal(catalog.eligiblePhotos({},'2026-09-23').some(item=>item.kind==='solar'), true);
  stars.configureRoom('paper-a', {prototype:'玉兔'});
  let view=(await stars.getRoomStarView()).data;
  const result=await stars.recordCompanion(view,{paper:true,random:()=>1});
  assert.equal(result.paperPhoto.id, 'outing');
  assert.equal(result.awardedStars,10,'照片不改基础奖励');
  assert.equal(stars.getPendingPhotos().length,1);
  stars.collectPhoto('outing'); stars.collectPhoto('outing');
  assert.equal(stars.getMemories().length,1);
  assert.equal(stars.getMemories()[0].collected,true);
  assert.equal(stars.getPendingPhotos().length,0);
  const balance=(await stars.getRoomStarView()).data.star.balance;
  assert.equal(stars.exchangePhoto('exchange',false).ok,false,'未加载不扣星');
  assert.equal((await stars.getRoomStarView()).data.star.balance,balance);
  assert.equal(stars.exchangePhoto('exchange',true).ok,true);
  assert.equal((await stars.getRoomStarView()).data.star.balance,balance-10);
  assert.equal(stars.exchangePhoto('exchange',true).duplicate,true);
  assert.equal(stars.getMemories().length,2);
  stars.configureRoom('poor', {prototype:'锦鲤'});
  await stars.getRoomStarView();
  assert.equal(stars.exchangePhoto('exchange',true).error.code,'INSUFFICIENT_STARS');
  assert.equal(stars.getMemories().length,0,'宠物隔离');
  console.log('纸条首次/33%/北京时间跨日/节气优先/去重/待收下恢复及兑换扣星边界通过。');
})().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{Date.now=originalNow;catalog.PHOTOS.splice(0, catalog.PHOTOS.length, ...savedCatalog);});
