const assert = require('assert');
const { THEMES } = require('../companion-theme-catalog');
const adapter = require('../iaa-star-unlock-adapter');
const { shanghaiDate } = require('../companion-star-rules');
const originalNow = Date.now;
let now = Date.parse('2026-10-04T23:59:59.999+08:00');
Date.now = () => now;
const art = {operations:[{type:'stroke',tool:'brush',points:[{x:1,y:2}]}]};
const image = '/tmp/user-original.png';
const approvals=THEMES.map(t=>t.approved);
const themes = THEMES.filter(t => ['K-R01','K-K03','K-A06'].includes(t.id));
themes.forEach(t => t.approved = true); // 独立测试进程 fixture，不改运行素材核对状态。
async function run() {
  adapter.configureRoom('theme-rabbit',{prototype:'玉兔'});
  let offer = adapter.getThemeInvitation();
  assert.equal(offer.theme.id, 'K-A06');
  assert.equal(adapter.beginThemeDrawing('hand-picked-duck').ok, false);
  adapter.beginThemeDrawing(offer.id);
  adapter.advanceThemeStep(offer.id,2);
  adapter.setCompanionDraft(art);
  await adapter.recordDrawingStart((await adapter.getRoomStarView()).data);
  assert.equal((await adapter.getRoomStarView()).data.star.balance,12);
  now += 1;
  assert.equal(adapter.getThemeInvitation().id,offer.id);
  assert.equal(adapter.getActiveThemeDrawing().step,2);
  const view = (await adapter.getRoomStarView()).data;
  let result = await adapter.recordThemeDrawingComplete(view,offer.id,{image},art,{roomIdentity:'theme-rabbit',themeRandom:()=>0.9,giftRandom:()=>1});
  assert.equal(result.ok,true);
  assert.equal(result.themeResult.tier,2);
  assert.equal(result.themeStars,4);
  assert.equal(result.giftStars,3,'首次小回礼仍必得，独立于主题抽奖');
  assert.equal(result.awardedStars,17,'画好基数10+小回礼3+主题惊喜4');
  assert.equal(result.data.star.balance,29);
  assert.equal(result.data.star.companionDays,1);
  assert.equal(adapter.getMemories().length,1,'无需收下，主题完成后自动入册');
  assert.equal(adapter.getMemories()[0].image,image,'收藏的是用户原画');
  const noRoll=()=>{throw Error('duplicate rerolled');};
  result=await adapter.recordThemeDrawingComplete(view,offer.id,{image},art,{roomIdentity:'theme-rabbit',themeRandom:noRoll,giftRandom:noRoll});
  assert.equal(result.awardedStars,0);
  assert.equal(adapter.getMemories().length,1);
  assert.equal(adapter.getThemeInvitation(),null);
  now+=86400000;
  offer=adapter.getThemeInvitation();
  assert.equal(offer.theme.id,'K-R01');
  adapter.beginThemeDrawing(offer.id);
  const started=await adapter.recordDrawingStart((await adapter.getRoomStarView()).data);
  result=await adapter.recordThemeDrawingComplete(started.data,offer.id,{image},art,{roomIdentity:'theme-rabbit',themeRandom:()=>0,giftRandom:()=>0.1});
  assert.equal(result.themeStars,1);
  assert.equal(result.giftStars,3,'主题普通档与小回礼命中仍叠加');
  assert.equal(result.awardedStars,14);
  assert.equal(adapter.getMemories().length,2);
  adapter.configureRoom('theme-koi',{prototype:'锦鲤'});
  offer=adapter.getThemeInvitation();
  adapter.beginThemeDrawing(offer.id);
  assert.equal((await adapter.recordThemeDrawingComplete((await adapter.getRoomStarView()).data,offer.id,{image},art,{roomIdentity:'theme-rabbit'})).ok,false,'旧房间回调不能结算新宠物');
  assert.equal(adapter.getMemories().length,0);
  assert.equal((await adapter.getRoomStarView()).data.star.balance,2);
  themes.forEach(t=>t.approved=false);
  adapter.configureRoom('unapproved-room',{prototype:'玉兔'});
  assert.equal(adapter.getThemeInvitation(),null);
  console.log('真实adapter主题开启、跨午夜恢复、双份基数/小回礼叠加、自动原画收藏、重复回调和宠物隔离通过。');
}
run().catch(error=>{console.error(error);process.exitCode=1;}).finally(()=>{Date.now=originalNow;THEMES.forEach((t,i)=>t.approved=approvals[i]);});
