const assert = require('assert');
const stars = require('../iaa-star-unlock-adapter');
const photo = { image: '/test-fixture-photo.webp', title: '窗边茶会', line: '本地测试素材' };
const options = id => ({ id, photo });
(async () => {
  stars.configureRoom('tea-test-rabbit');
  stars.resetRoomStarView('AVAILABLE');
  const initial = (await stars.getRoomStarView()).data.star.balance;
  assert.equal(stars.beginTeaActivity({ id: 'no-approved-photo' }).ok, false, '未提供照片不能开始');
  assert.equal(stars.getActivityState().current, null);
  assert.equal(stars.beginTeaActivity(options('tea-1')).data.current.cost, 0, '首次免费');
  assert.equal(stars.confirmTeaActivity().ok, false, '没选茶不能确认');
  stars.chooseTea('fixture-tea');
  assert.equal(stars.getActivityState().current.phase, 'confirming', '选茶不完成');
  assert.equal(stars.collectTeaActivity().ok, false, '第二次确认前不能收录');
  assert.equal(stars.beginTeaActivity(options('tea-other')).resumed, true, '退出后恢复原活动，不创建第二场免费活动');
  assert.equal(stars.getActivityState().current.id, 'tea-1');
  stars.confirmTeaActivity();
  assert.equal(stars.confirmTeaActivity().duplicate, true, '连点完成不重复结算');
  assert.equal((await stars.getRoomStarView()).data.star.balance, initial);
  stars.collectTeaActivity();
  assert.equal(stars.collectTeaActivity().ok, false, '重复收下不重复收藏');
  assert.equal(stars.getMemories().length, 1);
  assert.equal(stars.getActivityState().firstResultSeen, true);
  const view = (await stars.getRoomStarView()).data;
  await stars.recordDrawingStart(view);
  await stars.recordDrawingComplete(view, 'tea-test-drawing');
  const funded = (await stars.getRoomStarView()).data.star.balance;
  const paid = stars.beginTeaActivity(options('tea-2'));
  assert.equal(paid.ok, true);
  assert.equal(paid.data.current.cost, 20);
  assert.equal((await stars.getRoomStarView()).data.star.balance, funded, '完成结算策略开始不扣星');
  stars.chooseTea('fixture-tea');
  stars.confirmTeaActivity();
  stars.confirmTeaActivity();
  assert.equal((await stars.getRoomStarView()).data.star.balance, funded - 20, '完成只扣一次20星');
  stars.collectTeaActivity();
  const state = stars.getActivityState();
  state.firstResultSeen = false;
  assert.equal(stars.getActivityState().firstResultSeen, true, '读取快照不能修改资格');
  assert.equal(stars.beginTeaActivity(options('tea-3')).ok, false, '余额不足不能开启付费活动');
  stars.configureRoom('tea-test-koi');
  assert.equal(stars.getActivityState().firstResultSeen, false, '更换宠物隔离免费资格和活动进度');
  assert.equal(stars.getMemories().length, 0);
  stars.beginTeaActivity(options('tea-koi'));
  assert.equal(stars.getActivityState().current.paid, false, '任何开始入口均不提前结算');
  console.log('茶会内部流程：第二次确认、恢复、免费资格、重复结算、收藏和宠物隔离通过。');
})().catch(error => { console.error(error); process.exit(1); });
