const assert = require('assert');
const stars = require('../iaa-star-unlock-adapter');
let definition;
global.Page = page => { definition = page; };
global.wx = { showToast() {} };
require('../../pages/iaa-memory-album-demo/iaa-memory-album-demo');
const page = Object.assign({}, definition, { roomEntry: true, data: JSON.parse(JSON.stringify(definition.data)), setData(patch) { Object.assign(this.data, patch); } });
(async () => {
  stars.configureRoom('tea-page-test'); stars.resetRoomStarView('AVAILABLE');
  page.activityContext = { atHome: true, teaImage: '/test-photo.webp' };
  page.onStartTea();
  page.onChooseTea({ currentTarget: { dataset: { key: 'plain' } } });
  assert.equal(page.data.tea.phase, 'confirming');
  page.onConfirmTea();
  assert.equal(page.data.tea.phase, 'confirming', '照片未加载不能完成或结算');
  page.onTeaPhotoError(); page.onConfirmTea();
  assert.equal(page.data.tea.phase, 'confirming', '照片加载失败也不能完成');
  page.onRetryTeaPhoto(); page.onTeaPhotoLoad(); page.onConfirmTea();
  assert.equal(page.data.tea.phase, 'result');
  page.onCloseTea(); page.onStartTea();
  assert.equal(page.data.tea.phase, 'result', '关掉结果再开不重复参与');
  page.onTeaPhotoLoad(); page.onCollectTea();
  await Promise.resolve();
  assert.equal(page.data.teaVisible, false);
  assert.equal(page.data.memories.length, 1);
  page.onCollectTea();
  assert.equal(stars.getMemories().length, 1);
  stars.configureRoom('tea-away-test');
  page.activityContext = { atHome: false, teaImage: '/test-photo.webp' };
  page.onStartTea();
  assert.equal(stars.getActivityState().current, null, '外出不开始居家茶会');
  console.log('茶会真实页面：选茶、确认、照片失败重试、退出恢复、入册和外出限制通过。');
})().catch(error => { console.error(error); process.exit(1); });
